# -*- eval: (setq org-download-image-dir (concat default-directory "./static/737NG EEC 导致的右点火故障/")); -*-
:PROPERTIES:
:ID:       00FD3D0D-7DFF-468B-93E2-54DA5BC06816
:END:
#+LATEX_CLASS: my-article
#+DATE: <2021-01-21 Jan 22:24>
#+TITLE: 737NG EEC 导致的右点火故障

* 故障现象
:PROPERTIES:
:ID:       40BEBF4B-B1A3-4F60-9E10-4ED9DC984437
:END:
使用右点火，右发起动时，有燃油流量显示，但 EGT 不上升。
使用右点火起动右发失败。做 EEC 自检，无任何故障代码。考虑到右点火失效，影响飞机的放行，故决定停场排故。[fn:1]

[[file:737NG 起动刹车组件.org::*Engine does not start when using the right ignitor][Engine does not start when using the right ignitor]]

* 排故过程
:PROPERTIES:
:ID:       A3593EF4-D9EC-4A5A-8C8B-5A7DF1E0414C
:END:

- [[id:1D6928D0-6F61-4BD4-A363-AADF92D5D580][起动刹车组件]]内的两个点火电门
- 发动机起动电门
- 点火选择电门
- EEC

转换汇流条将 115 V 电源提供至左点火系统，备用汇流条将 115 V 电源提供至右点火系统。[fn:2]

提起动手柄至慢车位置时，点火控制系统实现以下控制：

- 115 V 转换汇流条、115 V 备用汇流条的交流电源分别通过两个闭合的点火电门送至 EEC。
- EEC 根据驾驶舱内的起动电门位置、点火选择电门位置来控制在 EEC 内部的四个点火 ON/OFF 电门。
- 四个点火 ON/OFF 电门控制 115 V 交流电被送至左、右点火激励器。
- 左或右点火激励器将接收到的 115 V 交流电转为 15,000 至 20,000 的高压电，高压电经过点火导线送至点火电嘴，以形成电火花。

根据故障现象和点火控制系统原理，我们对右发点火系统进行了以下排故工作：

- 做 EEC 自检，无任何故障代码。
- 检查点火导线和点火电嘴，发现左点火电嘴有一定程度的烧蚀，而右点火导线和点火电嘴正常。更换左点火电嘴。
- 检查右点火激励器的输入、输出电气接头，均正常
- 进入 EEC 自检页面，做右点火测试 3 次，每次都可以听到通道 A、B 工作时产生的响亮的点火声音。
- 将点火选择电门扳至“右”位起动右发数次，我们发现，有时可以起动发动机，而有时则没有点火而起动失败。
- 对调左、右点火激励器，将点火选择电门扳至“右”位，试车检查，也是有时可以起动，有时不能起动。再将点火选择电门扳至“左”位，试车检查，每次均能起动成功。说明两个点火激励器都能正常工作。
- 为了再次判断右点火激励器及其下游是否存在故障，按照 AMM74-00-00/901（MMEL 74-1 ([[id:D00702C1-F08B-440B-AB40-FAEAB3ABD1DF][DDPG]]) Preparation - Right Ignition System Inoperative），对调左、右点火激励器上游的点火供电导线。将点火选择电门扳至“右”位，试车检查，还是有时可以起动，有时不能起动。再将点火选择电门扳至“左”位，试车检查，每次均能起动成功。
- 根据步骤 2、3、6、7 的检查结果，我们认为右点火激励器及其下游是正常的，而在右点火激励器上游存在故障，即向右点火激励器提供 115 V 备用汇流条电源的上游线路出现了问题，所以，对于本故障，就不能通过对调左、右点火激励器上游的点火供电导线的方式来放行飞机。

从右发点火控制系统原理图中，我们看到，有可能导致右点火工作不正常：

- 起动刹车组件内控制右点火供电的 S91 电门可靠性差
- EEC 内的控制右点火供电的两个电门可靠性差
- S91 电门至 EEC、EEC 至右点火激励器之间的线路有问题
- 点火选择电门或其至 EEC 之间的线路问题

- 断开右点火激励器上游的点火供电导线，数次提起动手柄，测量出右点火激励器上游的供电电压都为 115 V，初步判断为起动刹车组件内控制右点火供电的 S91 电门可靠性差，最有可能导致此故障。
即：提起动手柄时，此电门有时可以闭合，有时不能闭合，导致有时有点火电源供至激励器，而有时没有点火电源提供给激励器，故时而可以起动发动机，时而又不能起动发动机。

- 考虑到更换起动刹车组件内的 S91 电门，难度较大。为了慎重起见，我们通过 EEC 自检测试，在 CDU 上“INPUT MONITORING”的“GMM DISGRETES”页面上读取发动机的点火信息。
在每次将点火选择电门扳至“右”位起动发动机时，不论是否起动成功，我们都注意到以下现象：
 - 在 EEC 自检测试的“INPUT MONITORING”的“GMM DISGRETES”第 2 页面里，IGNITER ENERGIZED 行均显示为“RIGHT”，这说明点火选择电门和其至 EEC 之间的线路是正常的。
 - 在 EEC 自检测试的“INPUT MONITORING”的“GMM DISGRETES”第 3 页面里，R IGNITER 115V 行均显示为“ON”，这说明提起动手柄时，有 115 V 的电源被供至 EEC，即 S91 电门及电门至 EEC 之间的线路是正常的。

- 根据上述检查及试车情况，我们认为，右发的 EEC 内部控制右点火供电的两个电门存在问题，同时，由于我们每次试车时都是 [[id:5E98E768-E584-42AB-BEEA-DAE114ED7712][EEC 的通道]] A 在工作，所以，确切的说应该是 EEC 内部控制右点火供电的通道 A 电门可靠性差。在起动发动机时，此电门有时闭合，有时不能闭合，导致有时有点火电源供至激励器，而有时没有点火电源提供给激励器。于是，更换右发 EEC，将点火选择电门扳至“右”位，多次起动发动机均成功。

* 排故总结
:PROPERTIES:
:ID:       FFF22E72-30C6-4398-A9F6-E7C4207CAD2C
:END:

本次由 EEC 导致的点火故障比较罕见，使排故耗时较长，主要表现在：

- 点火故障时隐时现，需要反复、多次的进行点火测试或试车，故障才可能再次出现，即使故障再次出现，也不能保证下一步的检查就能找到故障根源。如有几次在起动不成功后，我们立即进行线路测量，但是测量结果都是正常的。所以在对调点火激励器和激励器上游的供电导线后，通常要做两次以上的起动，以确保每次都能起动成功，但是通常是第一次起动成功，第二次或第三次则起动失败，这样就增加了试车次数，但不能确保故障彻底排除。
- 没有任何故障信息，增加了排故的难度。只能根据系统原理和线路图册，根据控制点火系统的部件的故障几率，从简到繁地逐个排除。

通过本次点火故障的排除，有以下体会：

- 在进行试车时，使用 EEC 自检测试的“INPUT MONITORING”的“GMM DISGRETES”页面，可以快速地确定有关部件如点火选择电门、起动点火电门是否工作正常。
- 对于右点火故障，不能根据故障现象，简单地按照 AMM74-00-00/901（MMEL 74-1 ([[id:D00702C1-F08B-440B-AB40-FAEAB3ABD1DF][DDPG]]) Preparation - Right Ignition System Inoperative），对调左、右点火激励器上游的点火供电导线来保留放行飞机。
首先必须确认故障根源出现在右点火激励器的上游还是下游：如出现在下游，则可对调左、右点火激励器上游的点火供电导线，保留放行飞机；如出现在上游，则不能放行飞机，须停场排故。

本人认为有 3 种方法来确认右点火故障根源所在：
- 如上所述，使用 EEC 自检测试的“INPUT MONITORING”的“GMM DISGRETES”页面。
- 检查右点火激励器、点火导线、点火电嘴。
- 进入 EEC 自检，做右点火测试，检查通道 A、B 工作时是否都可听到点火声。

* Footnotes

[fn:2] 在地面使用 GND 位单点火起动发动机的情况下，由于每次发动机运转时，仅一个 EEC 通道在工作，而每个 EEC 通道只控制一个点火 ON/OFF 电门的闭合或断开。
故每次提起动手柄时，只有一个点火 ON/OFF 电门闭合，以将转换汇流条或备用汇流条的 115 V 交流电送至左或右点火激励器。

[fn:1] 根据 MEL74-1，在右点火系统失效的情况下，按照 AMM74-00-00/901（MMEL 74-1 (DDPG) Preparation - Right Ignition System Inoperative），
可通过对调左、右点火激励器上游的点火供电导线，即把 115 V 备用汇流条由失效的右点火器转至可用的左点火器，这样就可以放行飞机。
但是，本次故障将说明，按照 MEL74-1 转换失效右点火来放行飞机是有局限性的，除非在转接点火激励器后，
只有在进入 EEC 自检页面做右点火测试时，通道 A、B 均可产生点火声且无点火故障信息，才可放行飞机。
