# -*- eval: (setq org-media-note-screenshot-image-dir (concat default-directory "./static/737NG 减速板手柄自动伸出慢或者伸出不完全/")); -*-
:PROPERTIES:
:ID:       754F102C-A9BB-4366-9863-0D08CD91E050
:END:
#+LATEX_CLASS: my-article
#+DATE: <2021-10-20 Wed 23:34>
#+TITLE: 737NG 减速板手柄自动伸出慢或者伸出不完全
* 故障现象
- 减速板手柄自动伸出慢或者伸出不完全
- PSEU 灯亮，显示 31-52108 GS PRESS A FAULT 和 31-52109 GS PRESS B FAULT 信息

* 可能原因
- 自动减速板作动筒本体故障
  驱动慢，负载能力低，内部离合打滑，切断电门故障，不能有效提供驱动力矩 Md。
  通过观察作动筒是否完全伸出进行隔离。

- 最大静摩擦力矩 Mfm 过小，导致手柄刹车打滑
 - 手柄刹车主间隙调节不合适，销钉，扇形片磨损，油脂污染使得刹车靴和扇形片的锁紧力不足。
   当负载或阻力力矩偏大时，二者之间容易出现打滑现象，导致作动筒的驱动力无法有效地通过手柄刹车传递至减速板手柄和驱动轴。此类故障可以通过调节手柄刹车主间隙或更换手柄刹车来解决。
 - 速度刹车手柄连杆或主轴轴承摩擦阻力过大，使手柄刹车上游阻力力矩 Mh 偏大，导致调节螺钉 C 和 D 压缩刹车靴的弹簧，降低刹车靴的锁紧力，使刹车靴和扇形片之间的最大静摩擦力减小，相应地 Mfm 减小，这种情况也会导致手柄刹车打滑。可以参考 FIM 27-62 Task 815 F(5) 或 737-SL-27-170-A 对速度刹车手柄的相关部位进行润滑来解决。

当 Md、Mfm 和 Mr 三者匹配时，手柄刹车才能正常作动。不同飞机之间的 Md、Mfm 和 Mr 会有所不同，不同飞机之间互串速度刹车作动筒或手柄刹车，可能会导致 Md、Mfm 和 Mr 三者不匹配而出现故障。因此，不建议通过互串刹车作动筒或手柄刹车来隔离故障。

造成自动速度刹车系统机械部分故障的主要原因有三个方面：作动筒驱动不可靠、手柄刹车锁紧摩擦力不合适、手柄刹车上下游的摩擦阻力过大，针对这三个
原因，可以根据实际情况制定相应的工程措施，以减少此类故障的发生。
- 自动速度刹车作动筒
目前 737NG 机队的自动速度刹车作动筒主要有 R5303M1 和 R5303M1-1 两种件号，二者之间可完全互换。厂家已发布 SB R5303M1-1-27-1，可将 R5303M1 升级为 R5303M1-1，新件号作动筒的离合器力值下限从 125 磅提高至 140 磅，改进了离合器销钉和切断电门的设计，
提高了作动筒的负载能力、寿命和可靠性。

某航空公司 R5303M1 的 MTBUR 值较高，在 25000-35000FH 之间，但年平均拆换率（含少量 R5303M1-1）连续几年上升，说明随着使用时间的增加，R5303M1 的可靠性逐渐降低，因此可考虑将 TSN 超过 20000FH 或连续两次 TSR
小于 500FH 的 R5303M1 作动筒升级为 R5303M1-1 作动筒，升级费用约为 3000 美元/个。

- 手柄刹车
目前 737NG 机队的手柄刹车有 50179-3 和 50179-3A 两种件号，此部件拆换率较低，50179-3 可以升级为 50179-3A，新件号的手柄刹车改进了刹车靴和扇形片组件的设计。厂家建议结合送修时进行升级。

- 手柄刹车上下游部件
手柄刹车上下游的机械部件主要包括减速板手柄及控制连杆、前扇形盘、控制钢索及滑轮、扰流板混合器及比例变换器、地面扰流板控制活门连杆、相关轴承等，随着航空公司机队逐渐步入老龄化，各类机械磨损越来越多，手柄刹车上下游部件的摩擦阻力可能变大，进而影响速度刹车系统的正常操作。
可考虑参考 AMM 手册定期对手柄摩擦力进行检查，并参考 737-SL-27-170-A 对手柄相关部位进行视情润滑；大级别定检时参考 AMM 手册对控制钢索张力进行校装，对磨损的滑轮、轴承等部件进行更换，以降低系统的阻力，减少和预防机械磨损导致的故障。
