# -*- eval: (setq org-media-note-screenshot-image-dir (concat default-directory "./static/8202-17 适航信息报告管理程序/")); -*-
:PROPERTIES:
:ID:   04E991BE-D371-4F6A-A06D-E3977E6BB496
:END:
#+LATEX_CLASS: my-article
#+DATE: <2022-07-27 Wed 20:26>
#+TITLE: 8202-17 适航信息报告管理程序
#+ROAM_KEY:
#+PDF_KEY: /Users/c/Documents/82维修工作程序手册/MF:8202-17-适航信息报告管理程序.pdf
#+PAGE_KEY:

* 1	基本信息 1
** 1.1	制定目的 1
** 1.2	依据文件 1
*** 1.2.1	AC-120-FS-060R2 “航空器适航与维修相关的信息报告和调查” 1
*** 1.2.2	AC-121-FS-2018-65-R1 “航空器结构持续完整性大纲” 1
*** 1.2.3	AC-121-FS-075 “公共运输航空运营人维修系统的设置” 1
*** 1.2.4	《维修工程管理手册》“向局方的报告” 1
*** 1.2.5	《维修管理手册》“维修记录与报告”、“生产控制” 1
** 1.3	程序属性 1
** 1.4	适用范围 1
** 1.5	定义及缩略语 1
*** 1.5.1	缺陷和不适航状况报告：指 CCAR145.34 规定的维修过程中发现或者出现的重大缺陷和不适航状况以及其他重要情况。 1
* 2	涉及岗位及部门职责 1
** 2.1	涉及人员岗位 1
** 2.2	部门职责 2
*** 2.2.1	航线维修部、基地维修部、福州维修基地 2
*** 2.2.2	质量部 2
*** 2.2.3	工程部 2
*** 2.2.4	发动机管理中心 3
*** 2.2.5	生产计划部 3
*** 2.2.6	航空器材部 3
* 3	工作规定 3
** 3.1	使用困难事件报告的规定 3
*** 3.1.1	使用困难上报范围：按照《维修工程管理手册》“向局方报告”第 1.1 条航空器使用困难报告的相关要求执行。 3
#+transclude: [[id:6F833B13-998B-4540-8907-817C2F241E49][向局方报告]] :level 4
*** 3.1.2	运行和检修中的飞机发生或发现使用困难事件时，事件处理单位应及时将事件报告生产计划部 MCC，报告的主要内容包括：飞机号、运行/检修种类、航班代码/检修编号、阶段、涉及的主要系统、故障的现象、程度和部位、机组采取的预防/紧急措施、排故措施等。其中 ETOPS 关键系统及结构类事件按附件 2“机务使用困难报告单”填写后报 MCC。 3
*** 3.1.3	涉及结构类事件时：在厦门，超出持续适航文件规定范围的修理由工程部工程处确认后，再由基地维修部工艺技术处向 MCC 报告；在福州，由维修工程师向厦航飞机维修工程部生产计划部 MCC 报告，由 MCC 转发工程部工程处确定是否超出规定范围，工程处确认超出规定范围后，由福州工程师填写使用困难报告表向 MCC 进行报告。 3
*** 3.1.4	在执行补充结构检查大纲过程中，当发现任何 CCAR121 部要求的重要结构项目或其相邻的疲劳裂纹时，通过 SDR 向局方报告，缺陷发现时间定为工程师收到信息报告并完成判断的时间。 3
** 3.2	使用困难报告技术调查信息的规定 3
*** 3.2.1	航空运营人应当立即对每一发生或者发现的使用困难报告开展技术调查，技术调查应当至少确定如下信息： 3
*** 3.2.2	即使上述要求的信息不能完全提供，航空运营人也至少在发生或者发现使用困难报告后 72 小时之内上报技术调查报告已经进展的内容，并在之后尽快补充报告没有提供的信息。 4
*** 3.2.3	上述报告应当以电子文件的方式上传到规定的局方系统，并经过主管维修监察员（PMI)的审核确认。 4
** 3.3	机械原因中断使用汇总报告的规定 4
*** 3.3.1	航空运营人在运行期间应当在每月 10 日前上报机队上月的如下机械原因中断使用  汇总数据： 4
** 3.4	缺陷和不适航状况报告的规定 4
*** 3.4.1	影响航空器安全运行和航空器或部件适航性的重大缺陷和不适航状况有： 4
*** 3.4.2	厦航实施飞机检修过程中产生的缺陷和不适航状况采集 5
*** 3.4.2.1	飞机维修缺陷和不适航状况按发生地点和飞机所有人可分为： 5
*** 3.4.2.2	上述事件发生后，执行部门应及时上报生产计划部门、质量部门和工程部门。 5
*** 3.4.3	厦航飞机维修中和代理第三方非航线业务时出现的缺陷和不适航状况报告，在福州发生的、福州分签页能力申请异地维修中发生的由福州维修基地负责编写、提交、在 FSOP 系统中上报，并抄送福建监管局；福州以外地点发生的且非福州分签页能力申请异地维修中发生的缺陷和不适航状况报告，由基地维修部/航线维修部负责编写、提交，质量部负责在 FSOP 系统中上报。 5
*** 3.4.4	缺陷和不适航状况报告应在事件发生后 72 小时内向局方报告，在规定的期限内不能完成此表格的，应当先用传真、电报、电话及电子邮件等形式报告，并在随后以缺陷和不适航状况报告的格式提出正式书面报告。 5
** 3.5	故障、失效和缺陷(音响警告组件)的报告规定 5
*** 3.5.1	运行和检修中的飞机发生或发现音响警告组件出现冒烟或有诸如电路板烧蚀痕迹、过热烧灼、线路损坏等故障时，事件处理单位应在 2 小时之内将事件报告质量部质保处，报告的主要内容包括：飞机号、涉及的主要设备、故障的现象、故障发生的时间、故障出现的地点、初步原因分析等。 5
** 3.6	年度报告和航空器引进计划的规定 5
*** 3.6.1	每年 1 月 15 日前，填写“维修单位年度报告”并上报局方，报告内容自上一年度 1 月 1 日至 12 月 31 日。报告数据应准确、真实，填写清晰。 5
** 3.7	维修差错事件的报告规定 5
*** 3.7.1	对于运行中发生航空器使用困难报告涉及的维修差错事件时，质量部安全处应及时通报 MCC 和可靠性中心，MCC 应及时在局方网站进行事件上报。 5
*** 3.7.2	对于运行中维修单位或航线维修代理单位发生的维修差错事件，质量部安全处应及时通报 MCC，MCC 应及时在局方网站进行事件上报。 5
*** 3.7.3	对于飞机投入运行前维修单位或航线维修代理单位发生的造成严重后果的维修差错事件，质量部安全处应及时通报 MCC，MCC 应及时在局方网站进行事件上报。 5
*** 3.7.4	对于上述 3.7.1/3.7.2/3.7.3 涉及的维修差错事件，质量部安全处应及时报告局方 PMI。 6
** 3.8	航线维修放行人员工作时间报告的规定 6
*** 3.8.1	航线维修放行人员工时报告的范围： 6
*** 3.8.2	航线维修部、基地维修部及福州维修基地应按照上述报告范围于每月 15 日前完成上一个月度本单位“航线维修放行人员工作时间月报”统计并报告至质量部质保处； 6
*** 3.8.3	各单位航线维修放行人员工作时间月报应完整、准确、真实，同时至少包含本程序 7.2 “附件 2 航线维修放行人员工作时间月报”（JW8202-17-02）中相应数据、字段，同时以 EXCEL 表格形式进行统计报告。 6
*** 3.8.4	质量部在每月 20 日前应将上一月度厦航飞机维修工程部所有航线维修放行人员工作时间按照局方要求上报至局方。 6
* 4	操作流程 6
* 5	工作记录 11
* 6	流程图 12
* 7	附件 13
** 7.1	附件 1：音响警告组件故障报告表样式 14
** 7.2	附件 2：机务使用困难报告单样式 14
** 7.3	附件 3：航线维修放行人员工作时间月报 14
