# -*- eval: (setq org-download-image-dir (concat default-directory "./static/8203-40 非例行工卡管理工作程序/")); -*-
:PROPERTIES:
:ID:       2A0D6ED1-3635-4AC1-AE20-410B637637E5
:END:
#+LATEX_CLASS: my-article
#+DATE: <2020-12-01 Tue 16:11>
#+TITLE: 8203-40 非例行工卡管理工作程序

* 3.工作规定

** 3.1 因飞机故障缺陷、维护接近、健康系统告警、计量器具超差追溯、航材装机证实和结构修理，可由资质人员在 SAP 系统按照操作流程生成相应 NRC。

** 3.2 飞机定检（A 检或 C 检）过程中，针对例行或非例行维修检查时发现的飞机缺陷/故障，由检验人员制订 NRC。

** 3.3 在航线运行中的飞机，针对机组反映或机务检查发现的缺陷/故障通常记录在航线维修记录本/客舱维修记录本上进行控制。对于因航材、工具设备、停场时间等原因需推迟维修的缺陷，航线维修部提出申请，由检验人员制订 NRC。
在航线运行中的飞机，针对健康系统告警类工作、计量器具超差追溯工作、拆下航材装机验证工作和风挡缺陷监控工作，由维修工程师根据需要制定 NRC。

** 3.4 风挡缺陷监控 NRC 由维修工程师制定、编写维修方案和关闭，无需流转。

** 3.5 飞机在定检期间，拆装类 NRC 由工艺工程师制订，定检工卡工艺准备时由工艺工程师根据需要制订 NRC。

** 3.6 缺陷/故障类 NRC 至少应包含的信息有：飞机号、机型、营运人，日期、检修号（若有）、关联例行/非例行工卡号（若有）、ATA、专业、是否 RII 项目、缺陷/故障描述、报告人。

** 3.7 若缺陷涉及结构件，须在系统中生成结构损伤报表，至少包含的信息有：

*** 3.7.1 飞机信息：发现损伤时的飞机使用时间、部件使用时间（限于可更换结构件）：

*** 3.7.2 损伤的信息：结构损伤类别、部件名称、部件属性、部件位置、部件件/序号、损伤和维修涉及范围和尺寸信息、工作内容描述等。应明确定义损伤的位置，对于蒙皮、桁条和隔框上的改装需用机身站位和桁条位，客舱地板梁则需使用机身站位 BS、剖线站位 BL，对于其他部件或位置则应参考适用机型飞机 SRM 的结构位置描述方法进行清晰定位描述。

（注: 准确表述损伤位置，包括利用机身站位 BS、剖线站位 BL、水线站位 WL、桁条位 S 等，需要说明的是，对空间曲面的飞机结构，通常是要三维坐标方可定位，也即机身站位 BS、剖线站位 BL，水线站位 WL 才能定位；
然而实际上，不同部位的损伤，位置的记录方式可以有所不同，例如：蒙皮、桁条和隔框上的损伤可以用机身站位和桁条位；客舱地板梁则可使用机身站位 BS、剖线站位 BL)

*** 3.7.3 施工方案的信息：是否重要修理、是否超出持续适航文件修理、损伤容限分类、非损伤容限分类、需重复检查项目的要求（若有） 、执行文件号。

** 3.8 属于必检项目的 NRC 应注明“RII”标志，并由检验人员进行检查、签署。

** 3.9 属于双维护项目的 NRC 在封面上应有双维护标识并注明适用左或者右系统。

** 3.10 工程师编制 NRC 方案时对 ETOPS 关键系统、双重维护工作、EWIS 及 CDCCL/AWL 维护工作进行评估和确认, 若维护工作涉及 EWIS 及 CDCCL/AWL 的在务，执行方案中应有相应的保护和警告说明 / 信息。

** 3.11 非例行工作的分级、分类、类别的含义、确定标准和要求参见《维修标准作业手册》“非例行工作项目分类规定”。NRC 施工方案编写实行“就高不就低”原则，即低级别 NRC 可以按照较高级别 NRC 施工方案编写要求编写方案，高级别 NRC 严禁按照较低级别 NRC 施工方案编写要求编写方案。

** 3.12 对于需要编写施工方案的 NRC，两个工作日内在生产计划与控制系统内完成编写施工方案。
