# -*- eval: (setq org-media-note-screenshot-image-dir (concat default-directory "./static/CMR/")); -*-
:PROPERTIES:
:ID:       FF188531-A79C-4A9D-85DF-2115F3112C4C
:ROAM_ALIASES: 审定维修要求 "Certification Maintenance Requirement"
:END:
#+LATEX_CLASS: my-article
#+DATE: <2022-02-16 Wed 22:26>
#+TITLE: CMR

#+ROAM_KEY:


* 定义
:PROPERTIES:
:ID:       3E9084D4-8ECB-46E8-BCAA-FA13C2B9D62A
:END:
按照 CCAR25.1309 要求，对运输类飞机的系统进行安全性分析和评估时，提出了故障探测要求，以防止危险性和灾难性故障发生。 
对这些要求经过进一步评审，被确定为审定维修要求（CMR），作为适航取证的重要内容，并向用户公布，以便正确地执行和监控。

CMR 是用来证实某一失效是否已经发生，但并不提供任何预防性维修工作的功能。
对于潜在失效，CMR 项目的任务是通过证实该项目没有失效而“将其失效终恢复至零”，或者如果已经失效则使之修理。

随着飞机复杂程度的增加，导致了飞机系统安全功能增多，这就必须考虑故障对飞机及其乘员的安全性影响，
必须考虑系统的一个或多个功能丧失，以及该功能可能导致其它系统损坏等情况。

为此，适航规章规定了系统故障发生的概率与危险程度之间的关系，必须对系统进行安全性分析。
若系统故障概率达不到所要求的数值，而改进设计又不可能或不经济，就必须增加故障探查工作，以发现和消除已存在的危险性后果。 
这种为发现重大潜在失效所做的检查工作，就是审定维修要求。

CMR 是航空器制造厂家用定量分析方法来表明满足 CCAR25.1309 的审定要求而规定的一种维修检查要求。 
审定维修要求是用来探查对安全有重要性影响的潜在失效，该种失效与一个或多个其它特定失效或事件结合起来，会造成危险性或灾难性失效状态。

* CMR 的制订程序
:PROPERTIES:
:ID:       75138A66-F1CA-4388-80D4-4912314FC50F
:END:
GMR 的制订程序和 MRB 报告的制订程序是截然不同的，前者是型号审定过程，后者是维修大纲的逻辑分析和判断过程。但它们之间又有非常密切的联系。

CMR 的制订程序如下：
1) 要列出所有潜在的危险性或灾难性的失效状态及其相关的任务。
2) CMR 候选项目的评审，由型号申请人召集审定维修要求协调委员会（由制造厂、用户代表、审定机构代表和 MRB 主席参加) 会议，
对 CMR 候选项目进行评审，以确定最佳的维修检查要求。

3) 由型号申请人将评审后的 CMR 项目，交工业指导委员会研究，将部分项目并入 MRB 报告（列入第 8 类)，
不能或不适宜并入 MRB 报告的项目，列入 CMR 项目。

4）将 CMR 项目提交负责型号审定的审查办公室进行最终审定和批准。批准后的 CMR 项目，列入型号审定数据单或以单独的批准文件发给有关单位。

* CMR 项目的管理
:PROPERTIES:
:ID:       77CD7D67-71FB-4483-A813-0319EFE107C7
:END:
CMR 项目应在单独的 CMR 文件中列出，并在型号合格证数据单中提及，成为型号审定数据单的重要组成部分。同时，也应列入 MRB 文件或 MPD 中。

CMR 文件上应清楚标明两种 CMR 工作：
a，一个星 CMR 项目（*） 一一规定的维修工作和时间间隔是强制性的，未经负责审定的飞机审定办公室的同意，不得更改、延长或取消。
b，二个星 CMR 项目（**） 一一用户可以按照批准的延长方法或批准的可靠性方案对维修工作间隔进行调整，但是在未经飞机审定办公室批准以前，不得更改或取消该项工作。

由于 CMR 项目是基于统计平均值和可靠度产生的，因此，对于在一架飞机上某一特定时间段内进行某一个单独 CMR 的时间间隔的特殊的短期延长，是不会危及飞行安全的。

维修大纲（MRB）或维修计划文件（MPD）的维修项目，列入了 CMR，但要用星号或注释标明，同时将 CMR 编入大纲的附录或制造厂编写的 MPD，以便于对审定维修要求的管理，也便于用户参照。

CMR 项目将由制造厂与各自的适航当局讨论决定。TC 取证后，制造厂对 CMR 项目的更改，也必须经审定维修协调委员会审定，并经审定办公室批准。
之后，通过颁发适航指令和 CMR 更改版通知用户，强制执行。


* CMR 的变更
在取证以后对 CMR 项目的任何更改都应通过维修审查委员会的评审，且必须得到批准型号设计国家的飞机审定办公室的批准。
引入新的 CRM 项目或对已有的 CMR 项目进行任何更改，应经过与初始审定采用的同样的过程进行评审。
而只有在设计更改时才允许取消相应的 CMR 项目。设计更改所产生的新的 CMR 项目，加入 CMR 文件。

一星 CMR 规定的维修工作和时间间隔是强制性的，未经负责审定国的飞机审定办公室批准，不得更改、延长或取消。

二星 CMR，用户可以按照批准的延长方法或批准的可靠性方案对维修间隔进行调整，但是在未经飞机审定办公室批准以前，不得更改或取消该项目。但是必须注意，二星 CMR 时间间隔的延长不能超出系统安全评估规定的最大值。同时，多次重复检查表明没有失效的发生并不能作为延长时间间隔或删除 CMR 任务的充分条件。

而对于单架飞机的单个二星 CMR 项目维修间隔，由于某种特殊原因不能按时完成，在特点的时间内，
运营人可以向局方申请“特殊的短期延长”。
而这种“特殊的短期延长”不能用于机队的类似 CMR 项目，同时也不能重复使用。
