# -*- eval: (setq org-media-note-screenshot-image-dir (concat default-directory "./static/doc 9859 安全管理手册/")); -*-
:PROPERTIES:
:ID:       375F820D-47EF-4E8A-BE15-67F86C48D4AC
:END:
#+LATEX_CLASS: my-article
#+DATE: <2022-01-10 Mon 21:34>
#+TITLE: Doc 9859 安全管理手册

#+ROAM_KEY:


* 引言
* 安全管理的基本内容
** 安全概念及其演变
** 系统中的人
** 事故的起因
** 管理因素
** 安全风险管理
* 安全文化
** 引言
** 安全文化与安全管理
** 发展积极的安全文化
* 安全绩效管理
:PROPERTIES:
:ID:       4455E0E1-B704-4482-AD21-BADED4DFF918
:END:
** 引言
** 安全目标
** 安全绩效指标和安全绩效目标
:PROPERTIES:
:ID:       D12B28D3-851B-46A5-8870-54CCE24A4002
:END:
*** 定性和定量指标
4.3.1.1 安全绩效指标用于帮助高级管理层了解组织机构是否有可能实现其安全目标; 它们可以是定性的，
也可以是定量的。定量指标涉及以数量而不是质量来衡量，而定性指标是描述性的，并以质量来衡量。定量指
标优于定性指标，因为它们更容易计数和比较。指标的选择取决于可定量衡量的可靠数据的可获性。必要的证
据必须是可比较、可概括的数据（定量），还是对安全状况的描述性说明〈定性） ？ 每个选项，不论是定性还是
定量的，都涉及不同类型的安全绩效指标，需要一个周密的安全绩效指标选择过程。同时采用多种方法在许多
情况下很有用，可以解决由于采用单一方法而可能出现的许多问题。对于国家而言，定性指标的一个例子可以
是其某一部门服务提供者的安全管理体系的成熟度，对于服务提供者而言，则是对安全文化的评估。

4.3.1.2 定量指标可以表示为数字（X 次入侵） 或表示为比率（每 N 起降架次 X 次入侵）。在某些情况下，
用数字表示就足够了。但是，如果 *活动水平波动* ，则仅仅使用数字可能会造成对实际安全状况产生扭曲的印象。
例如，如果空中交通管制部门在 7 月份记录了 3 次高度偏离，在 8 月份记录了 6 次高度偏离，那么可能引起人
们对安全绩效显著恶化的极大担忧。但 8 月份的起降架次可能是 7 月份的两倍，这意味着每起降架次的高度偏
离，或者说比率，是下降而不是增加了。这可能会也可能不会改变审查的水平，但它确实提供了另一条对于数
据驱动的安全决策可能至关重要的宝贵信息。

4.3.1.3 因此，在适当情况下，安全绩效指标应该以一个相对的比率来反映，以衡量绩效水平，而不论活动水平如何。
这使得可以对绩效进行标准化度量，而不管活动是增加还是减少。
另一个例子是，安全绩效指标可以测量跑道入侵的次数。
但如果监测期间的起飞次数减少，结果可能会产生误导。一个更准确和有价值的绩效衡量标准是相对于起降架次的跑道入侵次数，例如，每 1 000 起降架次 X 次入侵。

** 检测安全绩效
** 安全目标的更新
* 安全数据收集和处理系统
* 安全分析
* 安全数据、安全信息及相关来源的保护
* 国家安全管理
* 安全管理体系
:PROPERTIES:
:ID:       3EDD22C1-4D1E-4207-BBC0-DF63B6331A08
:END:
