# -*- eval: (setq org-media-note-screenshot-image-dir (concat default-directory "./static/IATA 运行安全审计及在我国的实践/")); -*-
:PROPERTIES:
:ID:       4A2548A7-FE7D-4D53-A43C-E6CD1B059F42
:END:
#+LATEX_CLASS: my-article
#+DATE: <2022-02-15 Tue 17:09>
#+TITLE: IATA 运行安全审计及在我国的实践
#+ROAM_KEY:

IOSA 是在国际上被广泛承认和接受的一个评估系统，它为航空公司的运行管理与控制系统提供了一个标准化的审计项目，其目的在于提高全球性运行安全及减少各类运行审计数量。
它建立在国际公认的标准之上，并通过严格的质量保证流程来保障其目标的成功实现。

截止 2006 年 3 月底，全球累计有 150 家航空公司完成了国际航空运输协会（IATA）运行安全审计（[[id:4328FC04-4840-4479-A944-A674A34760D4][IATA Operational Safety Audit]]，简称 IOSA），
它标志着 IATA 今后几年对其全部 265 家会员公司审计计划的良好开端。

我国上海航空公司于 2003 年底接受了 IOSA 审计，成为国内首家完成审计的公司。

随后，厦航、东航、深航、川航、山航等也相继完成了 IOSA，而南航、国航和海航目前还在进行之中。

其中，厦航于 2004 年 11 月以零不合格项的杰出表现，成为全球第 17 家获得 IOSA 注册的航空公司。

* 关于 IOSA 项目
:PROPERTIES:
:ID:       78D117F5-615F-4FB8-BC6E-6A2C5CBF1AA0
:END:
IOSA 的开发和目的为满足行业在削减成本和安全方面的需求，IOSA 项目于 2001 年 2 月启动。
当时，下辖于 IATA 的 IOSA 咨询小组负责项目的开发，专为此成立的 12 个工作组的 100 多名专业人员来自航空公司、政府监管当局、行业协会、审计、认证、法律等行业。
该项目在发起之初就得到了 IATA 会员、航空公司联盟和许多政府监管当局的全力支持和参与。
我国的厦航和海航曾派员参加了项目开发。经过两年多的努力，2003 年 6 月召开的第 59 届 IATA 年会批准 IOSA 项目投入使用。同年 9 月，全球首家运营人接受审计。

IOSA 项目的基本目的是减少大量存在于运营人之间的安全审计及改进运营安全。它为运营人带来了两个方面的利益：
一是在财务方面，IATA 希望通过推行单一和一致认可的审计标准、审计结果共享的项目来减少目的和内容重叠交错的重复审计，如替代目前大多数的代码共享审计，航空业将因此节省巨额的费用；
二是在运行安全方面，IATA 希望运营人通过遵守 IOSA 标准和建议措施来提升运行安全和效率。许多政府监管当局也认识到 IOSA 在帮助其延伸和提升安全监管方面的积极作用。
从 2005 底开始，IOSA 已成为运营人加入 IATA 的唯一安全资格审计。

* IOSA 出版物
:PROPERTIES:
:ID:       F44EAD8A-E986-4B37-B152-D4128259AF31
:END:
IOSA 的主要出版物有以下 3 种，目前在 IATA 网站上有免费的下载版本：
- IOSA 标准手册（[[id:A3BD715C-EFFE-4980-BB3C-9ADCD468E49B][ISM]]）。
  它包含审计所使用的各类标准及审计检查单，为审计提供了必要的操作标准、建议措施和指导材料。
  其中的各类标准涵盖了许多 ICAO、FAA 和 JAA 的要求，以及业内现有审计程序的最佳实践。

  2005 年起，增加了“临时修订”（TR）以反映最新的政府法规和规章要求，TR 条款的内容在并入 ISM 之前持续有效。
  ISM 每年至少进行一次修订，当签订审计协议时，使用的版本将写入审计协议里并在审计中应用。

- 是 IOSA 项目手册（[[id:134B8CFB-D1C8-42DA-B147-462C7D1D6BE1][IPM]]）。
  它是在管理与实施该项目过程中指导 IATA 与审计组织（[[id:C55BC622-86DB-4CA6-B8AF-ED7581853E42][AO]]）所使用的标准，包含了管理 IOSA 项目各个方面的标准，是 AO 的认定、审计员的批准和项目其他重要方面的指南。

- 是 IOSA 审计员手册（[[id:652E0AF0-F301-4582-AB0D-8AC23E87CAA6][IAH]]）。
  它是审计员的操作手册，包含了适用于审计员的详细信息和指南。

* IOSA 监察委员会
:PROPERTIES:
:ID:       68128F9E-9E62-4CA1-BF6D-7011612B3DBF
:END:
IOSA 项目投入使用后，IOSA 监察委员会（[[id:977CA2C4-5DA2-480A-BB63-586C3F628189][IOC]]）替代原 IOSA 咨询小组，代表 IATA 进行项目的日常管理。
其职能是对项目进行监察与指导、负责建立和维护各类标准、编写 IOSA 出版物、保管 IOSA 注册身份和审计报告、管理审计报告中央数据库、
认证 AO 和训练机构、持续对整个审计项目进行质量监察以及组织相关的工作会议。

IOC 的日常办事机构是位于加拿大蒙特利尔 IATA 总部的 IOSA 项目办公室（IPO）。
目前，IOC 由 25 家会员航空公司和 10 个政府监管当局组成，中国民航总局名列其中。
而 IOC 会议也常常邀请行业内有代表性和有兴趣的机构作为观察员参加，如 [[id:6FE2C272-B3B4-491D-91EA-2678209C5825][ICAO]]。

IOC 每 6 个月举行一次工作会议，讨论和决议 IOSA 进程中的重大事项。
IOC 第 5 次工作会议（IOC/5）于 2005 年 9 月底在加拿大蒙特利尔举行，我国南航、东航和厦航应邀以观察员的身份列席了该次会议。

* 审计组织、审计员和审计小组
:PROPERTIES:
:ID:       9B765D0F-8D61-459D-85A8-902E837847A5
:END:
IATA 自身不进行 IOSA 审计，而是由独立的 AO 具体实施。
AO 必须满足严格的认证标准并取得 IATA 的资格认证。
IATA 采用严格和一致的程序，对每一候选组织的各项能力，包括技术、法律、财务和其他方面的能力进行全面的持续审查，目的在于确保所有 AO 达到制定的高标准。
2005 年 9 月，IATA 向位于爱尔兰都柏林的 Parc Aviation Ltd. 颁发了 AO 证书，这使得认证的 AO 数量达到了 7 家。
AO 名单可在 IATA 网站上查知，这些具有广泛地理分布的 AO 都可以提供全球性的审计服务。

审计员按经验、知识和所展示的技能从低到高分为：审计员、领队审计员和评审员三个类别。他们都必须符合相应的资格要求，接受经 IATA 认证的培训机构的培训并向 IATA 取证。

审计小组由 AO 派出，其成员只能由经 IATA 认证的审计员组成，其中有一名是领队审计员。

* IOSA 标准和建议措施 ISARPs
:PROPERTIES:
:ID:       520E2283-F09A-4EB2-979A-BE68732367AB
:END:
IOSA 审计的范围严格限定于 ISM 所包含的内容。
ISM 共分两大部分：
- 第一部分是 IOSA 标准和建议措施（[[id:57A30C28-71FA-4CE1-8EA4-30B25556AEFF][ISARPs]]），
  共分为 8 章：
  - 公司组织与管理系统（ORG）、
  - 飞行运行 （FLT）、
  - 运行控制/飞行签派（DSP）、
  - 飞机工程与维护（MNT）、
  - 客舱运行 （CAB）、
  - 飞机地面操作（GRH）、
  - 货物运行（CGO）、
  - 运行保安（SEC）。
  这 8 章涵盖了营运运行安全的各个方面。

- 第二部分是 ISARPs 的指导材料（GM），它解释了 ISARPs 的含义，或详述满足符合性的其他途径，是 ISARPs 的补充信息和指南。
  - ISARPs 条款分为两类：标准和建议措施。
    - IOSA 标准是强制性的审计项目，在对标准的陈述中始终含有“必须”（shall）的字样；
    - IOSA 建议措施是可选择的审计项目，在对建议措施的陈述中始终含有“应当”（should）的字样。

* 符合、不符合和不适用
:PROPERTIES:
:ID:       80164C34-80FE-46BC-B9CF-79DF001D98FB
:END:
符合和不符合是指由审计员根据运营人在文件化和/或实施方面的实际状况，判定是否满足 ISARPs 规范要求的状态。
由不符合得出的审计结论有两种： ~不合格项~ 和 ~观察项~ 。

不合格项由不符合 ISARPs 的标准（即“必须”）条款而得出，在取得 IOSA 注册资格前必须得到整改；
观察项则由不符合 ISARPs 的建议措施（即“应当”）条款而得出，仅作为建议，不影响 IOSA 注册资格的取得。

可见，在审计过程中，运营人 ~文件化和实施的事实证据~ 是符合或者不符合 ISARPs 条款的依据。

因此，充分理解文件化和实施两个术语的含义就极为关键。

- 文件化
  文件化（Documented）是指以运行参考书籍、手册或以其他的公司正式媒介出版和准确反映出相关规定的状态。
  要满足文件化的要求，ISARPs 适用的每条内容必须公布于受控的文件，如参考书籍、手册或类似的出版物之中，并必须得到运营人的批准。
  这些受控的文件必须有相应的修订和分发流程以确保相应的运行岗位人员始终可以使用现行有效的版本。

- 实施
  实施（Implemented）是指启动、整合、融合、部署、安装或使其成为运行系统的可用组成部分，并进行必需的监控和评定其持续有效性的状态。

审计员在判断 ISARPs 是否符合实施的标准时，利用以下任一方式来判断条款的内容是否由运营人得到确立：是运营人组织或运行活动中现行有效的组成部分；或作为签约或外包的运行功能。

此外，某些 ISARPs 条款的全部或部分可能不适用于运营人的实际运行功能。
不适用的条款是指其所涉及的运行功能对于运营人来说属于尚未具有和不要求具有的运行种类。

例如，某运营人没有进行双发延程运行（ETOPs），则有关 ETOPs 的审计条款对于该公司来说就不适用。但已外包的功能不在此列。

因此，ISARPs 的每个条款经审计后将由审计员得出 3 个可能的结论：符合、不符合和不适用，其对应关系见下页表格。

* 注册制度和审计结果共享
:PROPERTIES:
:ID:       E5BF18A7-6EC3-45A3-9BAA-DBF9C59A3BF8
:END:
IOSA 项目采用注册制度。

运营人一旦依照审计程序通过审计且证明已经完全符合 IOSA 标准，IATA 将把其列入 IOSA 注册榜并在 IATA 网站予以公布。
注册身份从现场审计末次会议起 24 个日历月内有效， 即每两年需要一次复审。

现场复审开始日不早于到期日前 4 个月，复审中所发现的不合格项则必须在 IOSA 注册资格到期日之前完成。

考虑到 IOSA 质量控制流程也需要一定的时间，实际上至少应该在到期日之前两、三周完成整改才能保证在到期日前完成复审注册。

AO 在圆满完成对某家运营人的审计后将向 IATA 递交一份正式的 IOSA 审计报告（IAR）。

IAR 由 IATA 中央数据库保管以达到审计结果共享的目的，有兴趣的公众可以查阅开放的 IOSA 注册榜来了解某运营人是否完成了 IOSA 审计，
也可以书面向 IATA 申请查阅某运营人的 IAR。

IAR 虽由 IATA 保存但受审计方永远是该报告的实际主人，报告的内容只有经受审计方特许才能对外公布。

* 审计费和注册费
:PROPERTIES:
:ID:       9AFF5356-1617-4B7F-AED3-7CA1B7F9E3A9
:END:
IATA 不制定审计费用标准，每家 AO 将根据审计所需的资源状况和其自身成本基数进行收费，最终的审计费用由运营人和选定的 AO 自行商定。
审计费可因运营人地理位置、规模、设施及所需的整改措施而有所不同。但运营人的规模大小不会对审计费用有重大的影响，因为审计标准的条款数目相同，即工作总量不会有明显的变化。

目前，典型的现场审计是 6 位审计员用 5 天时间来完成。
此外，还有预先审计、准备、草拟报告、行政管理和整改行为的跟踪和复核等工作。

IATA 对全球前 85 份审计报告进行分析后发现，现场审计日越多，不合格项数量越多。
据此，为保证审计质量，IPO 要求最少的现场审计（指正式审计）天数为 25 人*天。

实际的人*天数需要写入审计报告，少于 25 人*天的审计需要事先得到 IPO 的批准。

在第 59 届 IATA 年会上，IATA 全体会员航空公司曾承诺在 2006 年 1 月 1 日以前取得 IOSA 运营人注册身份，
但按 IOC/5 会议时的审计进度，预计截止 2005 年底仅能完成约 50% 会员航空公司的审计。

IOC/5 会议重新评估后确定的新截止期为 2007 年 1 月 1 日。
届时，未接受 IOSA 审计的运营人将可能被终止会员资格。此决议已经过 IATA 理事会审议批准。

相应地，IOC/5 会议也对 IATA 征收的 IOSA 注册费做出了决议：对会员航空公司，自 2006 年 1 月 1 日起，初始审计免费，复审将收费；
对非会员航空公司，自 2006 年 1 月 1 日起，初始审计和复审都将收费。

* 如何准备和接受 IOSA 审计
:PROPERTIES:
:ID:       A22EFE82-84C2-4C58-9C03-612C24D0E040
:END:
回顾 IOSA 在我国的实践，运营人准备和接受 IOSA 审计所需的时间没有办法一概而论，时间长短取决于内部准备和问题整改的快慢和质量。
按照工作内容和先后顺序，运营人在接受 IOSA 审计过程中一般需经历以下几个阶段：

** 拟订审计计划
:PROPERTIES:
:ID:       49CFE0DD-C86C-4A71-8BE4-08C198357781
:END:
运营人一旦决定接受 IOSA 审计，首先应拟订详细的工作计划。这个阶段的主要工作如下：
 - 联系 IATA，了解 IOSA 审计事宜；
 - 获取 [[id:A3BD715C-EFFE-4980-BB3C-9ADCD468E49B][ISM]] 和检查单。IPM 与 IAH 可自选，因为它们包括了审计的程序和方法，会对准备审计有帮助。阅读常见问题解答，了解审计的内容、要求和过程；

- 公司内部成立相应的工作机构，明确职责，将 ISM 相应部分分发到对口专题小组。从国内的实践来看，工作机构通常可如下设立：
 - 公司层领导小组：通常由公司负责运行工作的领导和主要运行业务部门的主管组成，职责是领导公司 IOSA 审计工作，监督审计进度按计划实施，对审计过程中遇到的问题予以决策解决；
 - IOSA 项目组：通常由公司负责航空安全或运行资格审定的部门牵头，加上各专题小组的负责人组成，职责是具体组织 IOSA 审计的实施、协调各个专题小组的工作进程、内外联络以及信息发布与传达；
 - IOSA 专题小组：通常可根据 IOSA 审计范围的 8 章内容相应设立 8 个专题组，其职责是内部符合性自查、落实整改、协助审计和人员培训；
 - 翻译小组：通常可在公司内部抽调一些熟悉运行业务的翻译人员组成，具体负责手册翻译和协助审计员进行现场审计；

— 通报局方，进行预先沟通。来自局方的支持必不可少，因为受审查的手册等文件都必须经批准或认可；

— 初拟工作计划和预算。制作预算时要考虑到现场审计后的审计跟踪和可能的现场复核；

— 了解各家 AO 基本情况，要求相关信息与报价，综合比较后选择 AO；

- 安排初步选定的 AO 做管理访问（现场考察）；

- 指定一名受审计方代表或联络员。

** 内部预先准备
:PROPERTIES:
:ID:       485A62D3-4BAE-4E15-9EF6-C765BE4D3721
:END:
内部预先准备的质量直接影响着整个审计的进程。这个阶段的主要工作有：

— 确定 AO；
— 利用 AO 管理访问的时机，商谈审计合同和审计计划；
— 签订三方审计合同（受审方、AO 和 IATA）和确定审计计划；
— 向 AO 提供如下资料（英文）：运行合格证类型、日期和编号；运行类手册清单；主要的运行管理人员名单（公司层和主要运行部门）；公司运行设施，如主基地、维修基地、模拟机训练设施等的地址清单；各审计地点地址清单；
— 建议运营人使用 ISM 检查单进行一次内部审计测试或差距分析，来判断是否为审计做好了准备，更重要的是它能帮助运营人找出需要改正或改进的地方。这就是常说的“两个符合性”自查，即：公司手册与 ISM 的符合性(“文件化”）；实际运行情况与公司手册的符合性（“实施”）；
— 问题整改、手册修订和人员培训；
— 主要运行手册的翻译；
— 建议按照 IOSA 检查单制作符合性申明。

** 接受现场审计
:PROPERTIES:
:ID:       E60AC948-0FA0-4FE8-AB4E-146BF86E3C70
:END:
如有需要，通常是初次接受 IOSA 审计或自身资源欠缺的运营人，AO 可提供自选的预先审计服务。

预审相当于是一次模拟审计，它能够帮助运营人更好地了解审计如何进行，它所使用的方法和内容与正式审计完全相同,
但其审计结论却不写入审计报告之中。

但预审增加了审计员的旅行次数和审计工作日，也就相应地增加了受审计运营人的审计费用。如先前已安排有预审，正式审计可视情适当减少所需的审计员或审计日数量。

现场审计是指预审或正式审计时在运营人运行设施现场所进行的审计。在现场审计之前至少一周，应当和 AO 密切联系，落实以下事宜：

— 商定审计活动内容和现场审计时刻表，包括：
 - 审计员旅行计划安排（来回程、外站代理人审计）；
 - 驾驶舱和客舱观察的日期和航班安排；
 - 模拟机训练观察的日期和行程安排；
——索取审计员护照复印件或个人信息，准备审计员通行证件；
——现场审计开始时首次会议的安排；
——每位审计员审计活动安排；
——安排现场审计场所、陪同人员、翻译（如需）；
——每日讲评场所（如需）。受审方在讲评时应尽量获得审计员的一些有益建议，以便于现场整改，但这些建议仅限于口头、非正式的评论；
——现场审计结束时末次会议的安排。末次会议必须安排在现场审计结束时召开。如强制性审计项目（即 ISARPs 标准条款）未完成，末次会议如期召开，未尽项目的审计需另行商定。

** 不合格项整改和 IOSA 注册
:PROPERTIES:
:ID:       C7330244-97AF-493E-8FB3-F6DD4D5530B7
:END:
整改工作主要是围绕不合格项进行，观察项的整改由受审计方自行决定。

不合格项的整改通常有现场整改和审计后整改两种形式。

IPM 第 5.7 节允许在现场审计阶段，只要在末次会议之前审计小组能够核实全面的和永久的整改措施可以得到完全的实施，这些曾发现的不合格项和观察项不必列入审计报告。
许多运营人曾充分采用了这种现场整改的策略，以提高整改效率。但现场整改的问题引起了 IOC/5 会议的广泛争议。

为了使审计报告充分、完整地反映审计实际状况，会议要求在现场整改中完成的不符合项必须完整地予以记录，涉及的条款清单也应列入审计报告。

审计后整改在方法上和现场整改没什么差异，但在过程上，由于 AO 的审计小组已不在现场，则变得更加繁琐和费时。

首先，按 IPM 的要求，在现场审计末次会议后 15 个工作日内 AO 将向受审方递交一份临时审计报告，内含详细的在审计过程中发现的问题。

- 双方在 30 天内须商定不合格项整改计划及其跟踪计划；
- 其次，受审方按商定的整改计划进行不合格项的整改，其中修订的手册等文件须得到局方或公司主管的批准或认可；
- 第三，按双方认可的方式如电子邮件、信函等，由受审方向 AO 递送经批准或认可的修订文件、相应的实施方案和实施情况的事实证据；
- 第四，由 AO 的审计员根据收悉的材料，做出是否符合的判断。如审计员认为有必要，则可能需要安排现场复核；
- 最后，待全部不合格项整改完成、得到复核之后，由 AO 宣布审计结束。

接受审计的运营人必须在现场审计末次会议起 12 个日历月的期限内完成不合格项的整改和复核。一旦完成，AO 将在 5 个工作日内书面通知 IATA，15 个工作日内向 IATA 提交书面审计报告。
IPO 在完成对审计报告的质量审核后，将受审计的运营人列入 IOSA 注册名录。

但 IOSA 注册身份的有效期则自宣布审计结束起生效至现场审计末次会议后的 24 个月。

* Footnotes
