# -*- eval: (setq org-download-image-dir (concat default-directory "./static/")); -*-
:PROPERTIES:
:ID:       6D6380BD-86E3-45A1-B327-FB8C0477C84E
:END:
#+DATE: <2020-05-21 四 05:51>
#+TITLE: PSEU 灯亮与起落架转换活门作动

* 背景:
2010-8-14 B-5215 在南昌短停 PSEU 灯亮，代码为 29-22001，在 PSEU 上可消除。
福州短停测试代码相同，读取详细信息，故障发生在空中，为间歇性故障，故障不可放行。
本打算消除故障信息，放行飞机，后发现该故障导致起落架转换活门作动，液压 B 系统向 A 系统串油，于是决定停场排故。

* 分析:
同时满足下列五个条件时起落架转换活门自动工作：

- 1. 飞机在空中
- 2. 起落架手柄不在 DOWN 位
- 3. 任一起落架未收上
- 4. 左发 N2<50%
- 5. 液压 B 系统有压力

从附页的图上可以看出，R564 继电器提供左发的运转信号，如果该继电器不激励，则 PSEU 认为左发 N2<50%。
在飞机起飞收起落架时，1，2，3，5 这四个条件都满足，只要第 4 个条件（N2<50%）满足，起落架转换活门就会转换，这时液压 B 系统给起落架收上提供压力。
而在飞机降落放起落架时，因为起落架手柄在 DOWN 位，转换活门又恢复到正常位，由液压 A 系统供压。
之所以出现串油，是因为起落架收放作动筒是非平衡型，即收上和放下方向的腔体截面不同。
起落架在收上时需要的力大，放下时需要的力小，所以作动筒设计成非平衡型，收上压力腔比放下压力腔截面面积大。
出现该故障的情况下，收上时 B 系统供压，压力油液供油多而回油少，所以 B 系统油箱油液减少；
放下时 A 系统供油，压力油液供油少而回油多，所以 A 系统油箱油液增加。
从飞机起飞收起落架到降落放起落架，就完成一次上述循环，使油液从 B 系统串到 A 系统。
查看当天工卡液压油量记录如下：

| 当日航前: | A  系统   88% | B  系统  91% |
| 南昌短停: | A  系统   88% | B  系统  92% |
| 当前油量: | A  系统  106% | B  系统  64% |

一次串油使 B 系统油量减少 27%。
故障在南昌短停出现，但当时油量却没有变化，所以可以断定该故障是在飞往南昌的航段起落架收上之后才出现的。

* 总结：
在地面时，发动机不运转，R564 继电器不激励，虽然 R564 故障无法激励，但和实际状态是一致的，所以 PSEU 认为当前不存在故障，这样就可以消除故障代码，灭掉 PSEU 灯。
一旦发动机开始运转，这个故障就会再次出现，而且导致液压系统串油。
虽然从 PSEU 上可以消除 29-22001 的故障，但一定要排除故障才能放行。这和一般的 PSEU 灯亮故障不同。

* TODO 待添加
SSM73-22-31
SSM29-23-11
SSM29-20-01
SSM32-30-00
