# -*- eval: (setq org-download-image-dir (concat default-directory "./static/")); -*-
:PROPERTIES:
:ID:       C6C72DC7-E19F-4DFB-8DF0-09EA86EBBAEA
:END:
#+LATEX_CLASS: my-article

#+DATE: <2020-06-08 Mon 14:37>
#+TITLE: 人是怎么废掉的


其实一个人平时努不努力是可以看出来的，通过他的行为，对事情的态度等等。

每天就想躺在床上，玩手机，热衷于关心“国家大事”却做不好身边的小事，比如帮父母做下家务，总是关心明星的私事，却过不好自己的生活，每天深更半夜还在电脑或者手机上“奋斗“，白天日上三杆还在和周公聊天。

原地打转和螺旋上升是不一样的，而且往往只有局外人才能感受到这种变化，当局者很难看到这种改变。

所以出现下面这些情况时，一定有有所警惕，今天是不是也在持续性变废.....

* 间接性努力向上，持续性混吃等死

自己其实很清楚自己想要什么，想要过什么样的生活。但每天就是拿着手机看各种鸡汤文学，要不就是靠睡觉来对未来进行憧憬，等睡醒过来却还是老样子。整日无所事事，全靠对未来的幻想撑起当下的生活。

总是告诉自己，先休息一下，明天再开始努力，结果明天过去还是这样。总是在朋友圈发一些励志鸡汤，现实中却是个颓废王者。

语言上的巨人，行动上的侏儒。一边对当下的自己不满，焦虑不安，却还是不肯作出改变。

* 沉浸在过去的辉煌/失败，无法自拔

总是想着自己曾经牛逼的战绩，不愿接受自己当下的平庸。

想着之前的自己，在大学的社团中混得风生水起。最牛逼的时候，几乎走在学校的哪个角落都会遇到熟人，打个招呼，感觉全世界都是自己的一样，然后自己就膨胀了。

后来换了一个环境，周围的一切对于我都是那么陌生，更别说认识几个人。于是整日对什么事情都提不起兴趣，总觉得身边的人都很无聊，没有意思。做事情也没有之前的热血沸腾。

还有一种就是沉浸在过去的美好中，不愿放过自己，放下过去。

尤其体现在感情中，朋友小 z 就是这样，因为失恋，每天以泪洗面。

有人陪的时候，就一个劲的向朋友倾述这段感情的点点滴滴，问我们，到底是不是自己做的有问题？没有人陪的时候，就偷偷的看前对象的各种社交动态，甚至卑微的找 ta 求复合。

不愿意放下自己，放下那些过去美好的回忆。每天上班就是各种打不起精神，宛如一具行尸走肉，上级交代的任务也是草草完成。

最终辞了工作，也没有复合，只让自己变得更加难受，让我们看着心痛。

再有一种就是陷入失败的漩涡中，无法自拔。

这种人一般内心十分自卑，一次尝试，一次失败就会让他们怀疑人生。他们觉得自己就是个废物，觉得好像别人好像什么方面都比自己要强，特别喜欢拿自己的缺点和别人的优点比较。

他们不知道自己想要什么 ，看到别人这个做的好就会想去模仿。但是由于惧怕失败，所以终究没有不敢开始。于是开始了最快的失败，即还没开始就已经失败。

* 只愿意在当下看得到回报的事情上下功夫，不愿意花精力在长远规划中

总是喜欢琢磨一些短期就能看到收益的事情，并借此来满足、麻醉自己的大脑。

例如，在当下，生活过得不如意的时候，就将这种心态转移到游戏中。通过游戏的胜利，段位的晋升，或者游戏玩家的羡慕来获得短期的满足快感，藉此来逃避现实。

或者通过看小电影或者其他的小说等，严重的还会选择更加刺激堕落的方式，来转移对当下生活的注意力，逃离生活中平庸的自己。

而对于需要做长期规划的事情，需要忍受当下、忍受寂寞的事情提不起兴趣。总是抱着走一步算一步的心态。

很多机会就这样生生的错过。还总是感叹，我要是要知道这样，我一定好好做，结果还是在当下得过且过，没有看到丝毫行动。对生活中需要长期进行坚持，持之以恒的事情没有耐心与毅力。

例如早睡早起，看书，健身等等，很多人坚持了几天看到没有效果，就没有下次了，还有一些人甚至只是头脑中的开始。

* 总是习惯性的找各种理由拖延

每天明明有各种安排好的事情，却总是给自己找各种理由来拖延，最要命的是还理直气壮的拖的心安理得。

拖到最后的结果是怎样了呢？

要不是这件事情就从此放一边。

要不就是在网上顺便找一个敷衍了事。

（好好对比一下，你是不是也是这样)

要交的作业，总是等到最后一天才火急火燎的交完了事，要做的文案，总要等到最后上级再催才马马虎虎随便应付了事。
之前的时间，不是和同学在王者峡谷畅游，就是和同事在讨论下班去哪家餐馆吃饭。反正就是有各种理由。

* 拒绝阅读，拒绝新事物

每天的知识来源就是抖音、快手一些短视频平台。别人说什么就是什么，别人表达什么观点，就全盘接受，从来不去思考为什么，没有自己的判断能力。

总觉得别人说的都对，都有道理，别人说这个不对，也同样认同，完全被别人牵着鼻子走。好像别人放的屁都是香的一样。

* 随意透支自己的身体

总是觉得自己年轻，什么事情都能扛过一样。熬夜、抽烟、喝酒，只要开心，只要快乐，怎么伤害怎么来，反正还年轻，反正还身体好，从来不把自己的健康当一回事。
哪怕是晚上没有什么要紧的事情，也要拿着手机，打游戏、追剧。反正不看书也不学习。

心情不好，就约上几个好友，哪怕喝到吐了还继续喝，第二天还要上班，那又怎么样，总觉得自己年轻，喝完回去躺一下就好了。结果第二天既耽误了工作，自己身体还难受。

* 不愿意承认别人的优点，长处。总觉得对方成功是靠运气

不愿意承认对方比自己厉害，比自己努力，甚至不愿意承认对方的优点、长处，总觉得别人的成功都是靠运气的。

总是在别人取得成绩的时候去挑错，然后再用自己的长处对比别人的短处。

从来没有想过虚心向别人学习，甚至会想，把自己放到他那个位置，肯定做得比他更好。

之前一个很好的朋友说过他的一个故事。
他的数学成绩不好，每次考试分数都不高，同桌的数学成绩好，但是性格不怎么开朗，很内向。
每次开家长会，家里人说他和同桌的数学成绩时，他就会抨击同桌的性格，拿他的性格去和同桌比较，抬高自己，家里人每次都很生气。
后来真的被教育之后，开始正视同桌的数学成绩，还向同桌学习，数学成绩开始提高。
其实事实就是这样的，有时候你微不足道的一次帮助，真的就会让对方感激不已。

那种乐于鼓励他人，给他人掌声的人，很多时候都能从别人那里学到更多的知识，认识更多的朋友。

* 主次不分，生活混乱

拒绝一切社交活动，每天就想单纯的宅在家里，对外界发生的事情，一点兴趣都没有，只想安安静静的睡觉、玩手机、打游戏。

对于身边的父母等亲密关系也不懒得去经营，终日混吃等死，龟缩在自己的世界中无法自拔。
或者总是让一些没有营养的事情，没有价值的话题占据自己的生活中心。

 每天总想着怎么撩小哥哥小姐姐？
 总想着怎么回喷自己骂自己偶像的网络喷子？
 每天总想着怎么在网上说土味情话？

总想着脱单撩骚，却未曾想过脱贫致富。总是把自己的时间都花在这些无谓的事情上面，白白浪费自己的大好青春。

* 过度依赖他人

好像离开了 ta，饭都吃的不香了。

遇上事情，不管别人有没有时间，总给人家打电话或者发信息。把别人当成一颗挡风遮雨的大树。
不愿意独立面对问题，解决问题。遇到问题，自己首先想到的不是独立思考，而是找别人帮忙。
总来就没有想过自己独立解决问题，如果别人没有时间，会把问题放在一旁，继续自己的快乐生活，一直等到别人有空，再扔给他去解决。

* 极度短视，只顾眼前利益

无论做什么事情，只看的到眼前的蝇头小利。为了这一点点利益，乃至不顾兄弟情分。过河拆桥，总想着多捞一点是一点，无异于杀鸡取卵。

哪怕不是自己的，也要凑过去，硬抢一杯。眼里只有利益，没有感情。乃至为了自己的利益，与别人翻面不认人。

就像我写这个回答，不仅仅是想与你产生共鸣，然后你给我一个喜欢，或者随手一个赞，另一方面也是我未
来憧憬计划中的一环，当然你的认同会让我坚定越走越远的决心和勇气。

其实没有什么是一蹴而就的，人变废也是一样，需要一个过程。

这个过程可能比较缓慢，但往往很多时候不易觉察，或者是一些迹象初显端倪时，我们根本没有在意，等到反应过来已为时已晚。

短视，贪图享受，对什么事情都无所谓往往都是变废的开始。拖延，懒惰，无知，自我满足，不求上进，它们就像温水煮青蛙一样，慢慢的把你拉进深渊。

只要你开始堕落，你的能力，你的天赋就会以最快的时间被收走。

所以，不想让自己变成一个无用的人，就一定要时刻提醒自己，开始行动，立刻行动，不管是学习还是工作，都要立马开始，而不是一拖再拖。

看完这篇文章就可以立马行动起来了。

* 过分关注他人的评价，而且容易过度揣摩

想想生活中是不是是这样：

别人可能不经意的一句话或者一个动作，你会揣摩半天，还都是往不好的方面想。

比如，朋友半天不给你回信息，你就认为他是不是对你有意见，是不是不想和你说话。脑袋里会把这半个月的相处的回忆全过一遍。确认自己没有做错的地方。

他人对我们的评价固然重要，它让我们对自己的行为和语言有一个清楚的认知。但是过度的揣摩，不仅浪费自己大把的时间和精力，而且会破坏自己一天的好心情。

* 用钱总没有分寸，月月透支

我们总是习惯性的逃避痛苦，预支幸福。老想着在当下活得精精致致，潇潇洒洒。却不考虑自己日渐消瘦的钱包。

老活在自己臆想的世界中，直到每个月 1 号或者 20 号还款日的到来，才焕然醒悟。

看到喜欢的东西，买

看到别人都有的东西，买

看到广告中说的那么精致，买

好像没有买买买不能解决的问题。完全不考虑自己的经济情况，沉迷于电视里那种精致生活。

却无视自己钱包情况。

* 对自己的要求过高，达不到目标又过度自责

我们总是对自己的定位不够清晰，不知道自己的能力上限在哪里，盲目的给自己设定过高的目标，然后在日常的执行中总是达不到自己的目标后，又陷入深深的自责。

老是问自己，为什么别人能做到，自己却达不到，所以干脆不要做，又陷入日常的拖延当中。开始在变废的路上渐行渐远。

* 只学习，不输出

总是热衷于学习各种技能，却没有把哪怕一个技能做到极致。

总是觉得，这个技能有用，那个技能有用，却不知道自己的核心竞争力到底在哪里？所以遇到有这种学习机会的时候，总是会头脑一热，立刻报名。
学习了很久，却没有一项，可以拿的出手的技能。只能是学习上的王者，输出中的黑铁。

* 开始做一件事情，热衷于选择一个黄道吉日

比如，5.20 开始谈恋爱。
6.66 开始健身。
5.1 号开始练习写作。
或者五月最后一天听五月天的演唱会。

所以现在有大把的时候，吃吃吃，玩玩玩。任凭时间从自己的手上流逝。

等真到了黄道吉日，却因为这，或那的原因无限期延后。

* 习惯性的将原本简单的事情复杂化

总是用一些别人没听过的词汇去描述一些现象，好像这样就显得高级，显得自己有见识。

殊不知，真正厉害的人往往都是将复杂的东西简单化。比如上个世纪出现的卡片相机，就是将一些专业摄影设备的功能简化，让更多的人能够拍摄专业的照片。
所以在那样的时代背景下，拥有一台卡片机成为潮流。

* 不懂得断舍离，身边积累大量无用的东西

每次搬家或者大扫除，总会清理出很多不用的物品。习惯性都留在那里，好像丢了，之前的经历就白活了一样。

仔细检查一下，手机里是不是有很多三个月都没打开的 app。

仔细看一下你的桌子上，是不是有很多买回来就没有用过，或者一个月的使用频率低于五次的物品。

很多无用的东西，占据了我们太多的空间，人都是趋于习惯待在自己熟悉的地方，因为这些熟悉的东西会给我们安全感。在这些安全的环境中，人就会变得不思进取。

* 把自己的时间都贡献给了各种乱七八糟的圈子

今天这个兄弟组了一个局，明天那个兄弟出了一点事。每天的生活就是混在这些个圈子，别说什么成长，每天光应付这些杂七杂八的事情都搞不过来。

有时间陪各种兄弟，却疏于应付身边的亲密关系。有事情处理各种杂事，却没时间考虑自己的成长。

* 内心脆弱，当自己的理想和现实差距过大，或者到一个新环境中，落差太大，就接受不了

自己高中时，特别厉害，是学校里的小明星，但到了大学，就发现身边的同学都比自己厉害，一个个都能歌善舞的。
自己高中时的那种优越感瞬间就变成了挫败感。

在大学混的风生水起，尤其是成了一些社团的或者学生会的负责人，每天都有学弟学妹围着转，一毕业到了工作岗位，一个人处理那么多事情。
就受不了，上进心瞬时就变成了得过且过算了。

* 脸皮太薄，不懂的拒绝别人

每次同学也好，同事也好，朋友也好，只要请求帮忙，有求必应。明明这个事情，自己也搞不懂，但不懂的拒绝，只能自己委屈求全。
现学现用。

但现学现用的结果都不太好，最重要的是到最后费力还不讨好。
