# -*- eval: (setq org-media-note-screenshot-image-dir (concat default-directory "./static/民航不安全事件/")); -*-
:PROPERTIES:
:ID:       367BFF35-37E2-431A-A530-C57AFF1AC03A
:END:
#+LATEX_CLASS: my-article
#+DATE: <2022-01-18 Tue 14:29>
#+TITLE: 民航不安全事件
#+ROAM_KEY:

* 事故类不安全事件
- 民用航空器飞行事故
  飞行事故的定义和等级分类，按《民用航空器飞行事故等级》国家标准 GB14648-93 执行[fn:2]。
- 民用航空器地面事故
  航空地面事故的定义和标准，按《民用航空器地面事故等级》国家标准 GB18432-2001 执行[fn:3]。

* 事故征候类不安全事件
- 运输航空严重事故征候
- 运输航空一般事故征候
- 通用航空事故征候
- 航空器地面事故征候

飞行事故征候的定义、分类和标准，按《民用航空器飞行事故征候》民用航空行业标准 MH2001-2004 执行[fn:4]。

* 其他不安全事件[fn:1]
- 严重不安全事件
- 一般不安全事件

* 轻度不安全事件

* 航空安全举报事件

* 雷击未按时上报被处罚
海南航空因飞机遭遇雷击未按时上报，被民航华东局开出行政罚单。

据民航华东局 6 月 24 日最新消息，民航华东局对海航涉嫌信息迟报一事进行调查。
现已查明，今年 2 月 14 日，海航一架波音 737-800 飞机在执行 HU7591 航班（深圳至杭州)时遭遇雷击，但海航未按安全信息管理规定在 48 小时内填报事件信息，造成该事件信息迟报。

该份《民用航空行政处罚决定书》显示，上述行为违反了《民用航空安全信息管理规定》第 10 条：“事发相关单位和人员应当按照规定如实报告事件信息，不得隐瞒不报、谎报或者迟报”的规定，
现根据《民用航空安全信息管理规定》第 39 条：“企事业单位有下列行为之一的，由局方给予警告，或处 1 万元的罚款；情节严重的，处 2 万元以上 3 万元以下的罚款：
（一）违反本规定第十条，未按规定报告事件信息的；
（二）违反本规定第十四条，未按规定报告在我国境内发生的事件”的规定，
对海航予以警告的行政处罚。

* Footnotes

[fn:4]《CCAR-396 民用航空安全信息管理规定》

[fn:3]《CCAR-396 民用航空安全信息管理规定》

[fn:2]《CCAR-396 民用航空安全信息管理规定》

[fn:1]《民用航空其他不安全事件样例》
被《AC-396-AS-2016-08 事件样例》替代。
