# -*- eval: (setq org-media-note-screenshot-image-dir (concat default-directory "./static/浅析 C 检生产线的现场质量审核/")); -*-
:PROPERTIES:
:ID:       78B70FDE-4B81-4F48-90F0-1A095BE37A44
:ROAM_ALIASES: "Discussion on the On-Site Quality Audit for C-Check Production Line"
:END:
#+LATEX_CLASS: my-article
#+DATE: <2022-07-27 Wed 09:26>
#+TITLE: 浅析 C 检生产线的现场质量审核
#+ROAM_KEY:
#+PDF_KEY:
#+PAGE_KEY:

* 引言
某航司一架波音 737NG 飞机执行航班前，机组执行完正常开车程序，进行副翼和方向舵操作检查时发现，右侧副翼显示卡阻在向下位，无法回中，机组决定滑回检查，
机务打开盖板检查发现右副翼操作钢索断裂，断点位于右副翼扇形盘外侧滚轮处。

进一步检查发现，副翼操纵钢索在右副翼机翼扇形盘与滑轮之间处断开，端口处腐蚀严重，滑轮上有磨损痕迹，固定滑轮的支架磨损掉漆，有多处摩擦痕迹。

事件发生后的深入调查发现，该飞机在某维修基地执行上一次的 C 检时，本应进行副翼钢索的检查润滑工作，却由于工作者与检验员存在严重违章行为，未能按工卡要求执行该项检查工作，造成了重大隐患。

认识到该维修基地的 C 检质量存在严重问题后，航司质量系统迅速组织力量，分析梳理 C 检中容易发生质量问题的维修工作，研究制定 C 检质量提升方案及现场审核要点，
从 C 检施工质量入手，追溯 C 检工作的全过程全要素，通过纾解痛点、打通堵点、补齐断点，建立 C 检质量考核体系，以期推动维修系统 C 检维修质量的持续改善。

下文站在 C 检生产线现场质量审核的视角，从生产准备、按卡施工、生产控制、现场秩序等多个维度对 C 检维修质量进行深入剖析。

* 生产准备
在生产准备阶段，C检执行单位必须对人员、设备、器材、工卡和环境等生产要素进行充分地评估，以便 C 检维修的顺利开展。
若 C 检开工前未对准备完成的 C 检任务进行生产工作量化、过程分析，往往会导致这样一种局面：计划很漂亮，过程不受控，结果未知数。

在现场审核时，检查人员通常可通过以下几种常见的情形去判断 C 检执行单位生产准备是否充分。

- 特殊工装评估、培训是否充分、现场准备是否充分。例如，特殊封圈拆装工具无安装图示和操作指引，也未进行预先培训，工作者盲目施工易造成封圈安装不到位；C检开工前未根据工卡清单提前确认工具的在位情况。
- 工卡执行记录准备是否充分。例如，拆下/安装驾驶舱座椅套工卡，要求清洁不能超过 25 次，但工作者实际施工时无从得知座椅套的清洁次数；某份 EO 工卡备注建议第一次执行此 EO 的同时执行关联 EO，但工作者并不清楚该份 EO 是否为第一次执行。
- 复杂工卡预读学习是否充分。例如，一般目视检查风扇区域工卡，检查风扇叶片平台步骤中有执行过 SB 和没有执行过 SB 两种构型情况，现场审核中经常发现工作者对两种构型情况都执行了检查并签署；
  在执行详细检查襟翼滑轨上下法兰与滚轮接触表面的磨损深度工卡中，工作者对工卡中磨损标准理解有偏差，易造成测量错误。
- 工卡是否易于执行。例如，波音飞机的一般目视检查工卡任务描述过于宽泛，施工步骤过于简单，无明确的检查标准，易导致工作者对工卡内容理解出现偏差。
- 耗材航化品评估是否充分。如耗材航化品柜中的油脂过期。
- 等效替代评估是否到位。例如，拆装散热器时使用的吊具设备与工卡中要求的不一致，未按程序要求进行工具设备的等效替代评估。

生产准备不充分，主要问题几乎都出在对工卡的评估不充分上，生产准备往往基于年代久远的某一次历史评估数据，甚至于是兄弟单位的经验参考数据。
随之而来的，对于人力资源、工具设备、器材耗品等的匹配情况，C检执行单位通常很难掌握确切的数据。

工卡是航司为维护飞机而制定的、依据飞机制造厂的飞机维护手册、经实践证明为当前最佳的、安全有效的、达到了必要质量水平的标准作业方法，是飞机维护手册属地化、客户化的最重要体现形式。
工卡是维修任务的具象化，列明了详细、明确的施工步骤和检查标准。

在生产准备阶段，C 检执行单位应进行工卡评估，以保证工卡中的维修检查标准是现行有效的。
同时，还要安排工卡的预先学习时间，尤其是对于重、难、新工卡，应着重进行评估研究并宣贯分享，为在执行过程中避免错、忘、漏打下坚实基础。
针对必要的工具设备、器材耗品需求，则需制定合理的采购计划或系统内协调借用。

* 按工卡施工
通常，工作者或因知识、技能的不足，或因在生产准备阶段的培训、学习不充分，造成对工作任务的要求不熟悉、不理解，或因对简单、重复性工作的习惯性轻忽等因素，导致施工不到位。
在现场审核时，检查人员通常可通过现场观察到的几种常见情形去判断按工卡施工的状况。

- 清洁、润滑不到位。例如，检查发动机勤务总管工卡已执行完毕，但检查所涉及的管路接头仍有油泥覆盖；执行内侧襟翼润滑工作，丝杠螺母后端无润滑痕迹，没有新油从通气孔出来。
- 未正确执行施工步骤。例如，前缘缝翼润滑工卡，在恢复盖板安装工作时，现场检查发现缝翼在收上位，而工卡要求缝翼在放下位；
  在执行发动机燃油关断活门导线检查工卡时，工作者在其中一块吊架盖板未完全拆卸的情况下（工卡中要求拆卸该盖板进行检查），用反光镜完成了检查。
- 必检项目没有按要求实施。例如，执行反推前锁扣接近盖板和制动装置更换工卡，工卡中提到拆下前需要做标记，但现场抽查发现有检验员并不清楚此检查要求。
- 举手意识淡薄。例如，详细检查滑油滤回油滤网工作中，有步骤要求检查备用封圈安装方向是否正确以及是否有损伤，工卡参考图示有两种构型备用封圈，
  但工卡中未提及是哪一种构型。现场抽查发现，有部分工作者对于要检查哪种封圈构型及如何检查封圈安装方向是否正确均不甚清楚。

以上几种施工不到位的情况，究其原因，都是未严格按工卡施工造成的。要重视培养工作者的规章意识，就是要树立遵章守纪的底线思维，严格按照技术手册、工作单卡施工。
工卡作为标准作业方法，为维修人员施工和检查提供了一个共同的标准、一个基线，按工卡施工可以避免不必要的行为动作和无用功、确保流程顺利和目标达成、维持高质量、防止设备的损坏、降低成本、为维修人员工作交接提供连续性，是持续改善维修质量的基础和前提。
这也是要求持卡工作、逐项签署的原因所在。按工卡施工做得越好，对员工技能的依赖度越低，新员工也能越快上手。

C 检维修过程中，要重视简单、重复性工作，如目视检查前的清洁、润滑等工作，既要强化员工基本技能的熟练程度，又要强调认真、严谨的工作态度。
对工作者预先学习、熟悉工卡不到位的情况，维修单位要引起重视。

工作者学习工卡时间不够，容易忽略工卡信息栏的内容，从而造成学习工卡不全面。同时，也要注重培养工作者的举手意识。
工作者在维修工作中遇到异常情况、困难等无法进行下一步工作时要及时举手报告，寻求技术支援。对于操作性、执行性不强的工卡，可通过随手拍、现场报告、邮件报告等方式，向工程技术部门反映。

* 生产控制
生产控制是保证 C 检生产线能否按整体进度有序推进的中枢岗位。
任务计划、人员安排是否科学合理，对于 C 检生产线能否高效顺畅地推进实施有着至关重要的影响。
例如，每天需要安排多少工作量，每项工作需要多少工时、多少人力、需不需要加班等方面，都要提前做出科学的研判和部署。在现场审核时，检查人员通常可观察到以下几种常见的生产控制问题：

- 未根据 C 检实施情况及时调整更新 C 检流程甘特图，实际工作项目与计划工作项目不匹配；
- 工卡发放和回收未能有效匹配、一一对应，不能清晰、准确地真实反映 C 检进度；
- 实际工时记录不准确、统计不及时，不能真实反映当日人力资源和工时标准的匹配程度；
- 现场检验员配备不够，制约了检验员正常履职，也给工作者与检验员的协调配合带来了困扰。

生产控制环节的这些问题，反向体现出了对 C 检线生产控制人员的较高要求，
要求他们必须具备一定的专业技能、较丰富的专业经验，以及较强的沟通协调能力，并通过与各协作部门、一线工作者的密切联动，
随时掌握每日的任务完成状态以及具体的实施进度，并合理制定后续的生产控制计划，以期达成最大限度合理合规地利用人力、物力资源，追求效率化。

* 现场秩序管理
C 检生产现场的管理人员应围绕效率、质量、成本、安全等业务目标，分析现有生产、工作的全过程，分析哪些工艺流程不合理，分析生产、工作环境是否满足生产、工作需要和人的生理需要，
分析现场还缺少什么物品，针对不同类别场所的问题，分别提出改进建议并推进改进，使员工保持旺盛的斗志和良好的技能，所需物品易于接近、获取，不需要之物随时得到清除，
现场环境保持通畅、整洁、安全，使场所和环境在时间和空间上实现整体优化。C检生产现场管理不规范通常表现为以下几种状况。

- 工作现场耗材、航化品未进行有效管理。例如，航化品清单和实物不一致，部分航化品存储环境不满足要求。
- 器材未进行分区管理。例如，待修件和可用件混放、叠放，区域划分不明确；离位件挂牌不规范；静电敏感元件未按要求包装防护、存放。
- 工具管理制度落实不到位。例如，工具箱内物品和清单不一致；工作场所转移时工具清点落实不到位。
- 未正确使用警告标识和防护设备。例如，驾驶舱跳开关隔离未按工卡要求使用符合规格的跳开关夹；拆除克鲁格襟翼作动筒没有按工卡要求安装作动筒夹具。
- 安全风险防控意识不够。例如，进气道安装时未使用合适的工作梯，工作面太小易发生工作者踩空的风险；高空平台车在两架飞机间移动时，地面监护人员监护不到位。

针对 C 检生产现场的管理不规范情况，维修单位应充分利用现有厂房设施，合理规划维修现场航材存放区域，积极协调配置盖板存放架、存储箱/柜等设施，对航材进行分区、分类管理；
针对 C 检期间临时存放危险航化品的区域，要进行充分的安全评估；加强工作现场航化品的管控，解决工作现场航化品追溯性和有效期控制的难题；
加强风险防控培训、强化员工的施工环境风险意识，确保劳动保护设施设备到位，以避免人员受伤、航空器受损。

在 C 检期间，要重视开好班前会，重要信息应传达到全体工作者，内容至少包括当日工作内容、分工安排、高风险工作提示，并回顾前一日工作项目及风险源情况。

现场审核发现，工作者不规范行为被当场制止，对于工作者的触动是比较大的，如能即时辅以相应的培训教育，能使工作者更深刻地认识到问题，又能及时得到学习培训。

但进行即时培训不仅需要较高的业务能力（技能经验、品质意识、生产能力），还要有一定的理论知识和必要的表达能力。
现场审核观察到，部分生产现场管理人员在各方面条件上都有所欠缺，要么经验尚浅、要么意识不强，要么缺乏相应的理论知识或技能经验，
在发现工作者的不规范行为时往往只是简单说一下，有些甚至不能发现工作者的不规范行为，也就未能对工作者进行即时培训。
当然有时候还会因为时间冲突或不便中断工作，只能制止现场工作者的不规范行为，然后记录下来在班组会议时再作强调。

* 结束语
以上 C 检维修工作中常见的各种问题，可归纳为两个方面，一方面，这些问题不是在一个特定的时间点集中爆发出来的，而是经过了一个较长的时间跨度陆续表现出来的；
另一方面，在持续进行的现场质量审核中，绝大多数问题都被识别出来，且随后得到了很大程度的改善，最重要地，持续改善一直在进行中。

飞机维修作为一个高风险、高责任的技能密集型行业，维修工作特别是 C 检维修工作，点多面广、工艺复杂，技术标准要求高，这些特点决定了 C 检维修工作中必然会出现各种各样的问题。

在 C 检现场质量审核过程中，重点关注 C 检实施流程的标准化，探索解决维修标准落地的最后一公里问题，
如流程冲突、流程缺陷、工卡可操作性差、风险防控不当等问题，从而落实航司机务维修系统在一个标准统一的程序指引下开展维修工作，
尽可能弱化人员操作差异因素的影响，进而降低其所产生的额外管理成本。
