# -*- eval: (setq org-download-image-dir (concat default-directory "./static/游离态水/")); -*-
:PROPERTIES:
:ID:       77CC1014-2591-4512-BA59-F2AF7D074FE8
:END:
#+LATEX_CLASS: my-article
#+DATE: <2021-02-08 Mon 16:39>
#+TITLE: 游离态水

煤油能溶解水，这与水能溶解糖一样，只不过人们看不见。
燃油在一定温度下，最大溶水量是一定的。
如果燃油中的含水量小于最大溶水量，水分全部被溶解，那么燃油中只含有看不见的溶解态水。
如果燃油中的含水量大于最大溶水量，水分不能全部被溶解，那么有一部分水会从燃油中分离出来，形成可见的游离态水。
燃油的最大溶水量是变化的，它随温度增高而变大，也随温度下降而变小。
因此，当油温度升高时，燃油中的游离态水就有可能不见了；当油温降低时，即使原来是溶解态水也会有一部分又转化为游离态水，悬浮于油中或沉于油底。

当燃油中的溶解态水和油混为一体时，它对飞机燃料系统工作影响不大。
而当游离态水是以水珠或水团形式存在于燃油中时，危害就出来了。
大家都知道油箱中的微生物是滋生在水中的，油箱中一旦有水聚集就会引起微生物繁殖，微生物会导致油箱结构和部件腐蚀。
如果气温低于零度，这种游离态水还会结冰堵塞油路，影响发动机工作，后果不堪设想。
在 2008 年 1 月 17 日，时任英国首相戈登·布朗坐车赶往希斯罗机场，他即将展开上任后的首次访华活动。
他的车队在临近机场时，突然一架波音 777 客机呼啸而至，几乎贴着地面的高度坠毁在跑道尽头。
这就是著明的英航 38 号航班事件。经过局方深入的调查，最后发现此次事故的元凶就是燃油中的水分。
当飞机飞越西伯利亚上空时，燃油里的水结成了冰，零下 20 摄氏度时，它们开始累积在油管内部，自动驾驶仪设定飞机定速巡航，
冰的累积量也逐渐增加，在临近降落时，乱流迫使发动机提供更多动力支持，大量涌入的燃油冲出了燃料系统的冰晶。
大量冰晶堆积在燃油热交换器表面，导致了进入发动机燃烧室的燃油不足，双发失去动力，导致最终的事故发生。

所以燃料中决不允许有[[id:8AF1333E-CFA6-4710-877E-56EDF3B0508C][游离态水]]存在。

#+transclude: [[id:8AF1333E-CFA6-4710-877E-56EDF3B0508C][游离态水]]
