# -*eval: (setq org-download-image-dir (concat default-directory "./static/维修差错调查方法：MEDA/")); -*-
:PROPERTIES:
:ID:       442C684C-3FC5-4B53-A4A9-258D5C01878C
:END:
#+LATEX_CLASS: my-article
#+DATE: <2022-01-11 Jan 03:22>
#+TITLE: 维修差错调查方法：MEDA

* TODO 厦航维修差错（MEDA）调查表
[[x-devonthink-item://E0C80FEE-BF64-47F6-BBFB-0F391F8AEA23][调查表]]

* TODO AC-121-7 航空人员的维修差错管理
安全是一个相对的概念，ICAO 国际民航组织对安全的定义为： *安全是一种状态，即通过持续的危险识别和风险管理，将人员伤害或财产损失的风险降低并保持在可接受的水平或其以下。*研究人员发现，当前机械原因造成的飞行事故的比例已经由原来的 80%下降至 20%，人为因素会对飞机的安全构成更大的威胁。民航维修中任何疏忽和纰漏，都有可能造成严重后果，甚至发生机毁人亡的空难事故，这不仅影响民航空事业的发展，甚至还可能影响整个国家的经济发展和社会稳定。在 1992 年对英国的维护站点进行了研究之后，英国民航局汇编了以下最常见的维护错误列表：
组件安装不正确。
安装错误的部件。
电路接线错误。
遗留在飞机上的松散物品。
润滑不足。  
检修盖板、整流罩或整流罩未安装牢固。  
燃油盖或油箱盖以及燃油面板未安装牢固。  
滑出前未取下起落架锁销。

* MEDA 的基本理念
维修差错决断方法 MEDA（Maintenance Error Decision Aid）是波音公司开发的用于调查维修差错的一个重要的人为因素工具。
这一工具是以差错的发生是由于一系列的的事实或意外而导致的事实为基础。
运用 MEDA 的目的是调查差错，理解差错的根本原因，预防意外的发生，而不是简简单单地惩罚直接导致差错的人员。
传统的差错调查的目的往往是找出发生错误的员工。
在这种情况下，导致差错或者是意外的因素依然存在，错误仍然能够再次发生。
为了打破“惩罚---事故再次发生”的怪圈，MEDA 调查者尝试着找出导致差错发生的因素而不是找出导致差错的员工。
MEDA 是以以下三个基本假设为基础的：

- 维修人员想尽可能出色地完成任务而不是故意犯错。
- 差错的发生是由一系列的因素导致的。
- 导致差错的大多数的因素都是可以管理的

* MEDA 调查指导思想
MEDA 调查分析方法认为维修差错的发生有很多诱因，从当事人、维修管理、环境和组织结构等方面查找诱因，进而有效减少维修差错的发生。

MEDA 的调查指导思想如下：

- 任何人都有可能出现差错，在正常情况下，人是不会故意犯错误的，对于故意犯错的行为不在该调查范畴之内；
- 维修差错的发生，是由一系列因素诱发的，其中包括内因和外因。调查维修差错的目的就是要找出所有诱发因素，以便有针对性的制定预防和纠正措施，防止类似差错再次发生；
- 大部分诱因可通过管理与程序加以控制；
- 从低级别事件调查入手，改进管理，可预防更严重的事件的发生。

* MEDA 分析流程
波音公司联合英国航空，大陆航空，美国航空以及一个维修人员工会和 FAA 制定了实施 MEDA 的五个步骤：

- 确定所调查的差错维修单位必须从众多导致事故发生的差错中确定所要调查的差错
- 确定差错是否与维修相关只有确定差错是与维修相关的，MEDA 才能够继续 
- 进行调查借助 MEDA 调查表格，使用者能够进行一个调查用来记录飞机的相关信息：什么时候进行的维修，事故是什么时候出现的，导致事故的差错，导致差错的因素，引发调查的事故等
- 措施使用者评估，排序，使用，跟踪 MEDA 的改进来避免或者减少将来重复差错的出现的可能性
- 使用者必须将调查结果反馈给维修单位，并且使员工知道维修系统已经根据 MEDA 的调查结果做出了相应的整改。

* 管理解决方案
维护操作中的解决方案管理是成功实施 MEDA 的关键。
具体来说，管理者必须在开始调查之前对以下活动承担责任：

- 任命一名负责 MEDA 的经理并指定一个团队负责。
- 确定哪些事件将启动调查。
- 制定进行和跟踪调查的计划。
- 组建一个团队来决定要实施的预防策略。
- 在实施之前，告知维护和工程人员有关 MEDA 的信息。

正确的运用 MEDA，单位能够带调查出可能导致差错的因素，发生导致差错的真正因素，并且针对这些因素提出补救措施。
同时，这也能够帮助单位避免重复工作，利益受损和由于维修差错而导致的潜在的危险情景的出现。

* MEDA 的作用
采用 MEDA 管理理念后，除了有效减少维修中人为差错和事故外，还可以给各航空公司带来以下益处：

- 使机械原因造成的航班延误减少了近 20%；
- 改进了民航维修的工作程序和工作流程；
- 降低了飞机损坏事件的发生概率；
- 改变了管理中的“惩罚”惯性思维。

MEDA 流程可以帮助飞机的运营人识别造成维修错误的原因，以及将来如何防止类似错误。由于 MEDA 是用于调查导致错误的因素的工具，因此维护组织可以准确地找出导致错误的原因并补救这些因素。

下面结合近期国内民航维修企业中所发生的典型案例，使用 MEDA 理念对维修差错进行分析：

事件描述：
2010 年，某航空公司某飞机航后检查发现右发包皮维护盖板丢失。

决策：
与维修差错有关，可进行 MEDA 调查。

事件调查：
飞机起飞前由机务人员做航前检查。工作者打开维护盖板后去找润滑油，由于当时飞机正在上客，该工作者害怕影响航班正常起飞，就前往驾驶舱检查润滑油指示值和飞行记录本，
而忘记盖维护盖板，从而导致该盖板飞丢。

填写 MEDA 调查表格：
按照 MEDA 调查表相关要求填写 MEDA 表格。

纠正措施：
工作者：应严格按维修手册工作，防止工作被打断，工作后做好自查；
组织上：认真做复查工作，检验人员认真履行检验职责；
系统上：打开的盖板配备红色警告牌；
管理上：遗留工作要按要求做记录，交叉工作要做好工作交接。

反馈：
向相关人员提供反馈，并督察这些信息的落实情况。从以上案例可以看出，MEDA 是用于确定维修差错的诱导因素、以人为中心的系统调查方法。
不针对维修差错人员个体，而是由此从维修系统、组织和管理等各方面入手，深入分析事件本质，找出诱因，提出改进措施，从而防止以后再发生类似差错，最终将维修差错的管理变为有效的闭环管理模式。
因此可以说，MEDA 是目前把人为因素纳入维修系统工程比较成功的解决方案。实践证明，
MEDA 为减少民航维修中人为差错，提供了一套行之有效的解决办法，给当前民航维修差错管理提供了一定的指导和借鉴意义。
